### ISSUE TITLE
Doesn;t create folder is not exists

### ISSUE THREAD

**Issue by Dulanic** [PyCoding-A/Spotifarr#2]
Ran into this error....
```

 Updating database with 3 playlists: [Traceback (most recent call last):
  File "/home/dulanic/git/Spotifarr/main.py", line 9, in <module>
    spotify_c().update_playlists()
  File "/home/dulanic/git/Spotifarr/modules/spotify_db.py", line 82, in update_playlists
    "location": location_folder(clean_up_text(playlist['name']), self.path_music),
  File "/home/dulanic/git/Spotifarr/modules/config_handler.py", line 21, in location_folder
    os.mkdir(folder_playlist)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/btrfs/music/My Playlist'
(venv) abc@680a903a76d6:/home/dulanic/git/Spotifarr$ 
```

**Comment by Dulanic** [comment]
NM, didnt have my path mounted in my vscode container.
